modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
credits="Vazkii and quat, for writing the code :^)" #optional
[[mods]] #mandatory
modId="panoramamaker" #mandatory
version="1.0.0" #mandatory
displayName="PanoramaMaker" #mandatory
description='''
Standalone version of quark's panorama maker. Makes panorama pictures for main menu.
'''

# [[dependencies.panoramamaker]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.4]"
#    ordering="NONE"
#    side="BOTH"